---
title: "Shorebird and Waterbird abundance on Tomales Bay"
output: word_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE,
                      error = FALSE)
```


```{r}


library(tidyverse)
library(here)
library(birdnames)


custom_bird_list <- readRDS("C:/Users/scott.jennings/OneDrive - Audubon Canyon Ranch/Projects/my_R_general/birdnames_support/data/custom_bird_list")

options(scipen = 999)

sbirds <- readRDS("C:/Users/scott.jennings/OneDrive - Audubon Canyon Ranch/Projects/core_monitoring_research/shorebirds/ACR_shorebird_data_management/data_files/rds/shorebirds_for_analysis") 

sbirds <- sbirds%>% 
  filter(str_detect(season.year, "winter"))

sbirds_out <- sbirds %>% 
  mutate(alpha.code = "ALL_SBIRD") %>% 
  bind_rows(sbirds) %>% 
  mutate(season.year = str_replace(season.year, "winter_", ""),
         season.year = as.numeric(season.year))

wbirds <- readRDS("C:/Users/scott.jennings/OneDrive - Audubon Canyon Ranch/Projects/core_monitoring_research/water_birds/ACR_waterbird_data_management/data_files/working_rds/new_neg_machine_bay_total")


wbirds_out <- wbirds %>% 
  mutate(alpha.code = "ALL_WBIRD") %>% 
  bind_rows(wbirds) %>% 
  mutate(season.year = ifelse(month(date) == 12, year(date), year(date)-1)) %>% 
  rename(count = bay.total)


birds_out <- bind_rows(sbirds_out, wbirds_out) %>% 
  group_by(season.year, date, alpha.code) %>% 
  summarise(count = sum(count)) %>% 
  ungroup() %>% 
  group_by(season.year, alpha.code) %>% 
  mutate(annual.p75 = quantile(count, 0.75)) %>% 
  ungroup() %>% 
  mutate(common.name = case_when(alpha.code == "ALL_SBIRD" ~ "All shorebirds combined",
                                 alpha.code == "ALL_WBIRD" ~ "All waterbirds combined",
                                 TRUE ~ translate_bird_names(alpha.code, "alpha.code", "common.name"))) %>% 
  mutate(year.day = yday(as.Date(date)),
               winter.period = case_when(between(year.day, 304, 365) ~ "Nov-Dec", 
                                         between(year.day, 1, 31) ~ "Jan",
                                         between(year.day, 32, 60) ~ "Feb",
                                         TRUE ~ NA),
               winter.period = factor(winter.period, levels = c("Nov-Dec", "Jan", "Feb"))) %>% 
  filter(season.year < 2024)


```


```{r}

bird_plotter <- function(zalpha.code) {
  
  plot_df <- birds_out %>% 
    filter(alpha.code == zalpha.code)
  
  plot_title <- paste("Abundance of ", distinct(plot_df, common.name), "\non Tomales Bay, ", min(plot_df$season.year), "-", max(plot_df$season.year), sep = "")
  
  plot_df %>% 
    ggplot() +
    #geom_point(aes(x = season.year, y = count, color = winter.period), alpha = 0.5) +
    geom_point(aes(x = season.year, y = annual.p75), color = "black") +
    stat_smooth(aes(x = season.year, y = annual.p75), color = "black", se = FALSE) +
    theme_bw() +
    labs(title = plot_title,
         y = "Abundance",
         x = "Year") +
    scale_x_continuous(labels = seq(1990, 2025, by = 5), breaks = seq(1990, 2025, by = 5))
  
}


```

```{r}

bird_plotter("ALL_SBIRD")
```


```{r}

bird_plotter("ALL_WBIRD")
```


# Shorebirds

```{r}
bird_plotter("BBPL")
```


```{r}
bird_plotter("BLTU")
```

 
```{r}
bird_plotter("DOSP")
```

```{r}
bird_plotter("DUNL")
```

```{r}
bird_plotter("KILL")
```


```{r}
bird_plotter("LESA")
```

```{r}
bird_plotter("MAGO")
```

```{r}
bird_plotter("BLTU")
```

```{r}
bird_plotter("SAND")
```

```{r}
bird_plotter("BLTU")
```

```{r}
bird_plotter("SEPL")
```

```{r}
bird_plotter("SPSA")
```

```{r}
bird_plotter("WESA")
```

```{r}
bird_plotter("WILL")
```

```{r}
bird_plotter("YELL")
```
  
  
# Open water birds


```{r}
bird_plotter("AMCO")
```


```{r}
bird_plotter("AMWI")
```



```{r}
bird_plotter("BLSC")
```


```{r}
bird_plotter("BRAC")
```


```{r}
bird_plotter("BRAN")
```

```{r}
bird_plotter("BRPE")
```

```{r}
bird_plotter("BUFF")
```

```{r}
bird_plotter("CANG")
```

```{r}
bird_plotter("COGO")
```

```{r}
bird_plotter("COLO")
```

```{r}
bird_plotter("COME")
```

```{r}
bird_plotter("DCCO")
```


```{r}
bird_plotter("b.DCCO")
```

```{r}
bird_plotter("EAGR")
```

```{r}
bird_plotter("FOTE")
```

```{r}
bird_plotter("GADW")
```

```{r}
bird_plotter("GWTE")
```

```{r}
bird_plotter("HOGR")
```

```{r}
bird_plotter("MALL")
```

```{r}
bird_plotter("NOPI")
```

```{r}
bird_plotter("PALO")
```

```{r}
bird_plotter("PBGR")
```

```{r}
bird_plotter("PECO")
```

```{r}
bird_plotter("RBME")
```

```{r}
bird_plotter("RNGR")
```

```{r}
bird_plotter("RTLO")
```

```{r}
bird_plotter("RUDU")
```

```{r}
bird_plotter("SCAUP")
```

```{r}
bird_plotter("SUSC")
```

```{r}
bird_plotter("WCGR")